version: "3"
services:
  iot:
    image: ksivamuthu.azurecr.io/ksivamuthu/iot-app-docker-update:latest
    ports:
      - "5000:5000"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/ksivamuthu/.docker/config-watchtower.json:/config.json
    command: --interval 10