version: '3'
services:
  iot-app:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
